---
providers:
- name: openrouteservice
  base_url: https://api.openrouteservice.org/geocode
  key:
  limit: 40
  unit: minute
  endpoints:
    search: "/search"
    structured: "/search/structured"
    reverse: "/reverse"
- name: "geocode.earth"
  base_url: https://api.geocode.earth/v1
  key: 
  limit: 10
  unit: second
  endpoints:
    search: "/search"
    structured: "/search/structured"
    reverse: "/reverse"
